CPU_ONLY := 1
USE_OPENCV := 1
OPENCV_VERSION := 3
CUDA_DIR := /usr/local/cuda
BLAS := atlas
INCLUDE_DIRS := /usr/local/include
LIBRARY_DIRS := /usr/local/lib /usr/lib
BUILD_DIR := build
DISTRIBUTE_DIR := distribute
TEST_GPUID := 0
# enable pretty build (comment to see full commands)
Q ?= @
